#!/usr/bin/env bash
# This is the comment section

terminator()
{
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid
while true
do 
	echo "To infinity and beyond"
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'terminator' SIGQUIT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
done
