#!/usr/bin/env bash
# This is the comment
i=0
while [ $i -lt 21 ]
do
	case $i in
	4)
		echo $i
		echo "bad luck from China"
		;;
	9)
		echo $i
		echo "bad luck from Japan"
		;;
	17)
		echo $i
		echo "bad luck from italy"
		;;
	*)
		echo $i
		;;
	esac
	(( i++ ))
done
